package KieRule;
import insurance.premium.backend.Entity.Policy;

rule "Set base premium"
when

    policy : Policy(premium == null || premium == 0.0)
then
    
    policy.setPremium(3000.0);
end



rule "Add gender-based premium"
when

    policy : Policy(gender != null)
then

    if (policy.getGender().equalsIgnoreCase("male")) {
        policy.setPremium(policy.getPremium() + 1000);
    } else if (policy.getGender().equalsIgnoreCase("female")) {
        policy.setPremium(policy.getPremium() + 500);
    }
end


rule "Add tobacco user premium"
when

    policy : Policy(istobaccoUser == true)
then

    policy.setPremium(policy.getPremium() + 1000);
end


